/******************************************************************************************

Settings for ESLint 3.x

******************************************************************************************/

module.exports = {
	useEslintrc: false,
	"parserOptions": {
		"ecmaVersion": 6,
		"ecmaFeatures": {
			"impliedStrict": true,
		},
		"sourceType": "module",
	},
	// Find a list of rules at http://eslint.org/docs/rules/
	rules: {
		"comma-dangle": [ 2, "never" ],
		"no-cond-assign": [ 2, "always" ],
		"no-control-regex": 2,
		"no-debugger": 2,
		"no-dupe-args": 2,
		"no-dupe-keys": 2,
		"no-duplicate-case": 2,
		"no-empty-character-class": 2,
		"no-empty": 2,
		"no-ex-assign": 2,
		"no-extra-boolean-cast": 2,
		"no-extra-semi": 2,
		"no-func-assign": 2,
		"no-inner-declarations": 2,
		"no-invalid-regexp": 2,
		"no-irregular-whitespace": 2,
		"no-negated-in-lhs": 2,
		"no-obj-calls": 2,
		"no-regex-spaces": 2,
		"no-sparse-arrays": 2,
		"no-unexpected-multiline": 2,
		"no-unreachable": 2,
		"use-isnan": 2,
		"valid-jsdoc": 2,
		"valid-typeof": 2,
		"consistent-return": 2,
		"curly": [ 2, "multi-or-nest" ],
		"dot-location": [ 2, "property" ],
		"no-alert": 2,
		"no-caller": 2,
		"no-div-regex": 2,
		"no-labels": [ 2, { "allowLoop": true, "allowSwitch": true } ],
		"no-empty-pattern": 2,
		"no-extend-native": 2,
		"no-extra-bind": 2,
		"no-floating-decimal": 2,
		"no-implied-eval": 2,
		"no-invalid-this": 2,
		"no-iterator": 2,
		"no-labels": 2,
		"no-lone-blocks": 2,
		"no-multi-spaces": 2,
		"no-native-reassign": 2,
		"no-new-func": 2,
		"no-new-wrappers": 2,
		"no-new": 2,
		"no-octal": 2,
		"no-proto": 2,
		"no-redeclare": 2,
		"no-return-assign": 2,
		"no-script-url": 2,
		"no-self-compare": 2,
		"no-sequences": 2,
		"no-unused-expressions": 2,
		"no-useless-call": 2,
		"no-useless-concat": 2,
		"no-void": 2,
		"no-warning-comments": 2,
		"no-with": 2,
		"radix": 2,
		"wrap-iife": [2, "any"],
		"yoda": 2,
		"no-catch-shadow": 2,
		"no-delete-var": 2,
		"no-shadow-restricted-names": 2,
		"no-undef-init": 2,
		"no-undef": 2,
		"block-spacing": [ 2, "always" ],
		"brace-style": [2, "stroustrup", { "allowSingleLine": false } ],
		"camelcase": [ 2, { properties: "always" }],
		"comma-spacing": [ 2, { "before": false, "after": true }],
		"comma-style": [ 2, "last" ],
		"computed-property-spacing": [ 2, "never" ],
		"eol-last": 2,
		"indent": [ 2, "tab", { "VariableDeclarator": 1, "SwitchCase": 1 } ],
		"key-spacing": [ 2, { "beforeColon": false, "afterColon": true }],
		"new-parens": 2,
		"no-array-constructor": 2,
		"no-continue": 2,
		"no-lonely-if": 2,
		"no-mixed-spaces-and-tabs": 2,
		"no-new-object": 2,
		"no-spaced-func": 2,
		//"no-trailing-spaces": 2
		"object-curly-spacing": [ 2, "always" ],
		"operator-assignment": [ 2, "always" ],
		"quotes": [ 2, "double" ],
		"semi": [ 2, "always" ],
		"semi-spacing": [ 2, { "before": false, "after": true } ],
		"keyword-spacing": [ 2, { "after": true, "before": true } ],
		"space-before-blocks": 2,
		"space-before-function-paren": [ 2, "never" ],
		"space-in-parens": [ 2, "never" ],
		"space-infix-ops": 2,
		"space-unary-ops": [ 1, { "words": true, "nonwords": false }],
		//"spaced-comment": [ 2, "always", { "exceptions": ["-", "+", "*"] } ],
		"wrap-regex": 2,
		// ES6 rules
		"arrow-parens": [ 2, "always"],
		"arrow-spacing": [ 2, { "before": true, "after": true } ],
		"no-confusing-arrow": [ 2, { "allowParens": false } ],
		"no-dupe-class-members": 2,
		"no-duplicate-imports": 2,
		"no-new-symbol": 2,
		"no-useless-computed-key": 2,
		"no-useless-constructor": 2,
		"no-useless-rename": 2,
		"template-curly-spacing": [ 2, "always" ],
		"rest-spread-spacing": [ 2, "always" ],
		"no-global-assign": 2
	},
	globals: [
		"jQuery",
		"$",
		"angular",
		"require",
		"_",
		"window",
		"document",
		"localStorage",
		"setTimeout",
		"console",
		"he",
		"XLSX",
		"CSV",
		"moment",
		"fileSaver",
		"Big",
		"resizeDetector",
		"showdown",
		"rangy"
	],
	envs: [
		"browser",
		"es6",
		"jquery",
		"commonjs"
	]
};
